language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "iojs"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphicsmagick

before_script: chmod 0777 ./node_modules/.bin/mocha; chmod 0777 ./node_modules/mocha/bin/_mocha
script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage