language: node_js
node_js:
  - "stable"
  - "5.6"
  - "5.5"
  - "5.4.1"
  - "4.3.1"
  - "4.1"
  - "4.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick

before_script: chmod 0777 ./node_modules/.bin/mocha; chmod 0777 ./node_modules/mocha/bin/_mocha
script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
