language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "iojs"

before_script: chmod 0777 ./node_modules/.bin/mocha; chmod 0777./node_modules/mocha/bin/_mocha
script: ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./bin/coveralls.js --verbose